# 参考資料:https://answers.ros.org/question/283053/ublox-package-configuration/
# Configuration Settings for ZED-F9P device
debug: 1                 # Range 0-4 (0 means no debug statements will print)

device: /dev/ttyACM0     # ZED-F9P rover serial port
frame_id: gps

fix_mode: 3d                # Switches between 2D/3D automatically
dynamic_model: portable

config_on_startup: true # use chip config

rate: 5                     # Measurement rate in Hz
nav_rate: 5                 # in number of measurement cycles

uart1:
  baudrate: 230400       # serial port baudrate
  #baudrate: 115200  # serial port baudrate
  #baudrate: 460800  # serial port baudrate
  in: 32
  out: 3

# GNSS Config, verify which GNSS are supported by your device
gnss:
  gps: true                 # (not required since it defaults to true)
  glonass: true             
  beidou: true             
  qzss: true   
  galileo: true           
  sbas: false

inf: 
  all: true                   # Whether to display INF messages

dgnss_mode: 3                 # Fixed mode

# Message subscriptions
subscribe:
  all: true                 # Subscribe to all messages
  aid: 
    all: false                # ... except AID messages

# Enable u-blox message publishers
publish:
  all: false
  nav:
    all: true
    relposned: true
    posllh: true
    posecef: true